package cc.javaee.bbs.model;

public class Pic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbbs_pic.id
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    private Integer id;

//图片路径
    private String path;

    //帖子id
    private Integer tieziid;

    //板块id
    private Integer bankuaiid;

    //图片类型
    private String pictype;

    //创建人
    private Integer createuserid;

    //图片宽度
    private Integer width;


    //图片高度
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbbs_pic.isdel
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    private String isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_pic.id
     *
     * @return the value of jbbs_pic.id
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_pic.id
     *
     * @param id the value for jbbs_pic.id
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_pic.path
     *
     * @return the value of jbbs_pic.path
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_pic.path
     *
     * @param path the value for jbbs_pic.path
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_pic.tieziid
     *
     * @return the value of jbbs_pic.tieziid
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public Integer getTieziid() {
        return tieziid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_pic.tieziid
     *
     * @param tieziid the value for jbbs_pic.tieziid
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public void setTieziid(Integer tieziid) {
        this.tieziid = tieziid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_pic.bankuaiid
     *
     * @return the value of jbbs_pic.bankuaiid
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public Integer getBankuaiid() {
        return bankuaiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_pic.bankuaiid
     *
     * @param bankuaiid the value for jbbs_pic.bankuaiid
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public void setBankuaiid(Integer bankuaiid) {
        this.bankuaiid = bankuaiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_pic.pictype
     *
     * @return the value of jbbs_pic.pictype
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public String getPictype() {
        return pictype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_pic.pictype
     *
     * @param pictype the value for jbbs_pic.pictype
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public void setPictype(String pictype) {
        this.pictype = pictype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_pic.createuserid
     *
     * @return the value of jbbs_pic.createuserid
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_pic.createuserid
     *
     * @param createuserid the value for jbbs_pic.createuserid
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_pic.width
     *
     * @return the value of jbbs_pic.width
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_pic.width
     *
     * @param width the value for jbbs_pic.width
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_pic.height
     *
     * @return the value of jbbs_pic.height
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_pic.height
     *
     * @param height the value for jbbs_pic.height
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_pic.isdel
     *
     * @return the value of jbbs_pic.isdel
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public String getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_pic.isdel
     *
     * @param isdel the value for jbbs_pic.isdel
     *
     * @mbggenerated Mon Jul 10 12:45:19 CST 2017
     */
    public void setIsdel(String isdel) {
        this.isdel = isdel;
    }
}