package cc.javaee.bbs.model;

public class StopIp {
    private Integer id;

    //开始ip
    private String startip;

    //结束ip
    private String endip;

    //类型  -1,访问 -2,注册 -3,登陆 -4,发帖 -5,回复 
    private String type;

    //创建时间
    private String createtime;

    //创建人
    private Integer createuserid;

    //是否使用
    private String isuse;

    //备注
    private String remarks;
    
    //登陆名称
    private String loginname;

    
    public String getLoginname() {
		return loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_stop_ip.id
     *
     * @param id the value for jbbs_stop_ip.id
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_stop_ip.startip
     *
     * @return the value of jbbs_stop_ip.startip
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public String getStartip() {
        return startip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_stop_ip.startip
     *
     * @param startip the value for jbbs_stop_ip.startip
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public void setStartip(String startip) {
        this.startip = startip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_stop_ip.endip
     *
     * @return the value of jbbs_stop_ip.endip
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public String getEndip() {
        return endip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_stop_ip.endip
     *
     * @param endip the value for jbbs_stop_ip.endip
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public void setEndip(String endip) {
        this.endip = endip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_stop_ip.type
     *
     * @return the value of jbbs_stop_ip.type
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_stop_ip.type
     *
     * @param type the value for jbbs_stop_ip.type
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_stop_ip.createtime
     *
     * @return the value of jbbs_stop_ip.createtime
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_stop_ip.createtime
     *
     * @param createtime the value for jbbs_stop_ip.createtime
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_stop_ip.createuserid
     *
     * @return the value of jbbs_stop_ip.createuserid
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_stop_ip.createuserid
     *
     * @param createuserid the value for jbbs_stop_ip.createuserid
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_stop_ip.isuse
     *
     * @return the value of jbbs_stop_ip.isuse
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public String getIsuse() {
        return isuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_stop_ip.isuse
     *
     * @param isuse the value for jbbs_stop_ip.isuse
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public void setIsuse(String isuse) {
        this.isuse = isuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbbs_stop_ip.remarks
     *
     * @return the value of jbbs_stop_ip.remarks
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbbs_stop_ip.remarks
     *
     * @param remarks the value for jbbs_stop_ip.remarks
     *
     * @mbggenerated Fri Jul 14 17:21:09 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}